---
title: "sample"
always_allow_html: true
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

library(tidyverse)
library(RcppRoll)

```



## 移動平均

```{r, echo = TRUE}
iris_roll <- iris %>% 
  dplyr::mutate(roll_Sepal.Length = roll_mean(Sepal.Length, 
                                              n = 3L, 
                                              align = 'right', 
                                              fill = NA))
# 右端の列にSepal.Lengthの移動平均列ができている
DT::datatable(iris_roll %>% head(5), extensions = 'FixedColumns',
  options = list(dom = 't', scrollX = TRUE, scrollCollapse = TRUE))
```


---
## 移動平均

 - RcppRoll::roll_mean  :   
 https://qiita.com/Sickle-Sword/items/d93aff1d29e1176e25fe

   - nが窓の大きさ  
   - alignはleft, center, rightのいずれか。
   - fillは、窓が切り取れない行の最初とか最後とかを埋める値
 

---

## 図示


```{r, echo = TRUE, warning=F, fig.height=4, fig.width=9}
ggplot(iris_roll) +
  geom_line(aes(x = 1:nrow(iris_roll), y = roll_Sepal.Length), color = "red") + 
  geom_point(aes(x = 1:nrow(iris_roll), y = Sepal.Length), color = "blue") 
```

---
## lowess


```{r, echo = TRUE}
iris_lowess <- iris %>% 
  dplyr::mutate(lowess_Sepal.Length = lowess(Sepal.Length, f = 1/15)$y)
# 右端の列にSepal.Lengthのlowess列ができている
DT::datatable(iris_lowess %>% head(), extensions = 'FixedColumns',
  options = list(dom = 't', scrollX = TRUE, scrollCollapse = TRUE))
```


---
## lowess

 - stats::lowess :  
 https://ichi.pro/python-de-no-lowess-kaiki-de-tanai-no-meikakuna-pata-n-o-hakkensuru-hoho-wa-266555640085045  
 
   - pythonのページですがイメージはここが分かりやすい
   - lowess(ベクトル)で, x にインデックス, yにlowessの結果が返ってくる
   - 引数fで平滑化度合いを変えられる
   

---

## 図示

```{r, echo = TRUE, warning=F, fig.height=3, fig.width=9}
ggplot() +
  # 移動平均
  layer(data = iris_roll, stat = "identity", position = "identity",
        geom = "line", params = list(color = "red"),
        mapping = aes(x = 1:nrow(iris_roll), y = roll_Sepal.Length)) +
  # lowess
  layer(data = iris_lowess, stat = "identity", position = "identity",
        geom = "line", params = list(color = "blue"),
        mapping = aes(x = 1:nrow(iris_lowess), y = lowess_Sepal.Length))
```

---

## 2軸

```{r, echo = TRUE, warning=F, fig.height=3, fig.width=9}
second_rate = 1.5
iris %>% 
  dplyr::select(Sepal.Length, Sepal.Width) %>% 
  dplyr::mutate(index = 1:nrow(.),
                Sepal.Width = Sepal.Width * second_rate) %>% 
  pivot_longer(cols = -index, names_to = "params", values_to = "values") %>% 
  ggplot() +
  geom_line(aes(x = index, y = values, color = params)) +
  scale_y_continuous(limits = c(0, 10),
  sec.axis = sec_axis(~ . / second_rate, name = "2axis_Sepal.Width")
  ) + ylab("1axis_Sepal.Length")
```
---
## 2軸

 - scale_y_continuousで2軸作成できるようです。  
 ただ、自分で軸の高さを調整しないといけないので、  
 ミスする可能性もあります。  
 https://qiita.com/nozma/items/7e430994a2840aad645f


